declare module 'react-native-vector-icons/FontAwesome';
declare module 'react-native-vector-icons/MaterialIcons';
declare module 'react-native-vector-icons/Ionicons';
declare module 'react-native-vector-icons/AntDesign';
declare module 'react-native-vector-icons/Entypo';
declare module 'react-native-progress/Bar';
declare module '@react-native-async-storage/async-storage';
declare module 'sunrise-sunset-js';
declare module 'hijri-date';
